<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>NeutrinoOS.Drivers.Ext2</AssemblyName>
    <RootNamespace>NeutrinoOS.Drivers.Storage.Ext2</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../../../ddk/DDK.csproj" />
  </ItemGroup>

</Project>
