#!/bin/bash
# NeutrinoOS build-number stamp: increments .buildnum (repository root) and
# regenerates src/kernel/Generated/NeutrinoVersion.cs so the kernel (and the
# shell banner / uname / version builtin) reports the new "major.minor.build"
# version, e.g. "0.1.7".
#
# Invoked once per build by the build entry points:
#   - build.sh            (make image builds)
#   - build/wsl-rebuild.sh (WSL full rebuild, bumps the SOURCE repo first)
# Utility-only builds (p5-apps-build.sh) do not bump: utilities read the
# version from the kernel export at runtime.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NUM_FILE="$ROOT/.buildnum"
GEN_DIR="$ROOT/src/kernel/Generated"
GEN_FILE="$GEN_DIR/NeutrinoVersion.cs"

major=0
minor=1
num=0
if [ -f "$NUM_FILE" ]; then
    digits="$(tr -dc '0-9' < "$NUM_FILE" || true)"
    if [ -n "$digits" ]; then
        num="$digits"
    fi
fi
num=$((num + 1))
printf '%s\n' "$num" > "$NUM_FILE"

mkdir -p "$GEN_DIR"
cat > "$GEN_FILE" <<EOF
// <auto-generated>
// NeutrinoOS build version - generated by version-bump.sh.
// Do not edit by hand: build.sh / build/wsl-rebuild.sh regenerate this file
// and increment the build number (.buildnum at the repository root) on every
// build. Committed so a fresh clone builds without running the bump.
namespace ProtonOS;

/// <summary>Build-stamped NeutrinoOS version ("major.minor.build").</summary>
public static class NeutrinoVersion
{
    /// <summary>Major version.</summary>
    public const int Major = $major;

    /// <summary>Minor version.</summary>
    public const int Minor = $minor;

    /// <summary>Build number; increments on every build.</summary>
    public const int Build = $num;

    /// <summary>"major.minor.build" version string (e.g. "0.1.7").</summary>
    public const string ShortVersion = "$major.$minor.$num";
}
EOF

echo "NeutrinoOS version: $major.$minor.$num"
