// NeutrinoOS korlib - Async State Machine Attributes
// Compiler-generated attributes for async/await pattern.

namespace System.Runtime.CompilerServices
{
    /// <summary>
    /// Indicates whether a method is marked with the async modifier.
    /// </summary>
    [AttributeUsage(AttributeTargets.Method, Inherited = false, AllowMultiple = false)]
    public sealed class AsyncStateMachineAttribute : StateMachineAttribute
    {
        /// <summary>Initializes the attribute.</summary>
        public AsyncStateMachineAttribute(Type stateMachineType) : base(stateMachineType)
        {
        }
    }

    /// <summary>
    /// Indicates whether a method is an iterator method.
    /// </summary>
    [AttributeUsage(AttributeTargets.Method, Inherited = false, AllowMultiple = false)]
    public sealed class IteratorStateMachineAttribute : StateMachineAttribute
    {
        /// <summary>Initializes the attribute.</summary>
        public IteratorStateMachineAttribute(Type stateMachineType) : base(stateMachineType)
        {
        }
    }

    /// <summary>
    /// Indicates whether a method is an async iterator method.
    /// </summary>
    [AttributeUsage(AttributeTargets.Method, Inherited = false, AllowMultiple = false)]
    public sealed class AsyncIteratorStateMachineAttribute : StateMachineAttribute
    {
        /// <summary>Initializes the attribute.</summary>
        public AsyncIteratorStateMachineAttribute(Type stateMachineType) : base(stateMachineType)
        {
        }
    }

    /// <summary>
    /// Allows you to obtain the method or property name of the caller to the method.
    /// </summary>
    [AttributeUsage(AttributeTargets.Method, Inherited = false, AllowMultiple = false)]
    public class StateMachineAttribute : Attribute
    {
        /// <summary>Gets the type of the compiler-generated state machine type.</summary>
        public Type StateMachineType { get; }

        /// <summary>Initializes the attribute.</summary>
        public StateMachineAttribute(Type stateMachineType)
        {
            StateMachineType = stateMachineType;
        }
    }

    /// <summary>
    /// Indicates that a method is generated by the compiler.
    /// </summary>
    [AttributeUsage(AttributeTargets.All, Inherited = false)]
    public sealed class CompilerGeneratedAttribute : Attribute
    {
        /// <summary>Initializes a new instance of the CompilerGeneratedAttribute class.</summary>
        public CompilerGeneratedAttribute()
        {
        }
    }
}
