// ProtonOS DDK - TLS 1.3 server (Phase 6)
//
// Minimal RFC 8446 server implementation for the NeutrinoOS HTTPS
// capability: single certificate (Ed25519), key exchange via X25519,
// AEAD suites TLS_AES_128_GCM_SHA256 and TLS_AES_256_GCM_SHA384.
//
// Scope (documented in docs/PHASE6-TLS.md):
//   - no 0-RTT, no client certificates, no OCSP, no HelloRetryRequest,
//     no session tickets, no KeyUpdate (alerts on request), no TLS 1.2
//     (the required TLS 1.2 suites need RSA/ECDSA, which Phase 6 does
//     not implement - deferred to Phase 7).
//
// Everything is non-blocking and cooperative: the web service Tick()
// calls Step() and ReadApp()/WriteApp() as the socket becomes ready.

using System;
using ProtonOS.DDK.Crypto;
using ProtonOS.DDK.Kernel;
using ProtonOS.DDK.Network.Sockets;

namespace ProtonOS.DDK.Tls;

/// <summary>TLS 1.3 server connection state (see file header).</summary>
public sealed unsafe class Tls13Connection
{
    // Record content types.
    private const byte CtChangeCipherSpec = 20;
    private const byte CtAlert = 21;
    private const byte CtHandshake = 22;
    private const byte CtApplicationData = 23;

    // Handshake message types.
    private const byte HtClientHello = 1;
    private const byte HtServerHello = 2;
    private const byte HtEncryptedExtensions = 8;
    private const byte HtCertificate = 11;
    private const byte HtCertificateVerify = 15;
    private const byte HtFinished = 20;

    // Alert descriptions.
    private const byte AlertCloseNotify = 0;
    private const byte AlertHandshakeFailure = 40;

    private const int StateWaitClientHello = 0;
    private const int StateWaitClientFinished = 1;
    private const int StateConnected = 2;
    private const int StateClosed = 3;
    private const int StateError = 4;

    private readonly TcpSocket _sock;
    private int _state = StateWaitClientHello;

    // Certificate + private key (loaded/generated by the caller).
    private readonly byte[] _certDer;
    private readonly byte[] _keySeed;

    // Cipher suite parameters.
    private HashKind _hashKind = HashKind.Sha256;
    private int _hashLen = 32;
    private int _keyLen = 16;
    private ushort _suite = 0x1301;

    // Transcript (raw handshake messages, header included).
    private byte[] _transcript = new byte[2048];
    private int _transcriptLen;

    // Handshake secrets.
    private byte[] _clientHsTraffic;
    private byte[] _serverHsTraffic;
    private byte[] _clientApTraffic;
    private byte[] _serverApTraffic;

    // Record protection state: 0 = plaintext, 1 = handshake keys, 2 = app keys.
    private int _rxProtection;
    private int _txProtection;
    private byte[] _rxKey;
    private byte[] _rxIv;
    private byte[] _txKey;
    private byte[] _txIv;
    private ulong _rxSeq;
    private ulong _txSeq;

    // Buffers.
    private readonly byte[] _rx = new byte[18432];
    private int _rxLen;
    private readonly byte[] _hs = new byte[8192];   // reassembly for handshake messages
    private int _hsLen;

    private string _serverName;

    /// <summary>Server name from the SNI extension (null when absent).</summary>
    public string ServerName => _serverName;

    /// <summary>True once the handshake finished with the client.</summary>
    public bool Connected => _state == StateConnected;

    /// <summary>True when the connection is finished (closed or errored).</summary>
    public bool Closed => _state == StateClosed || _state == StateError;

    /// <summary>Negotiated cipher suite id (0x1301 / 0x1302).</summary>
    public ushort SuiteId => _suite;

    /// <summary>Wrapped socket accessor for the owning server.</summary>
    public TcpSocket Socket => _sock;

    /// <summary>Create a TLS server connection over an accepted socket.</summary>
    public Tls13Connection(TcpSocket sock, byte[] certDer, byte[] keySeed)
    {
        _sock = sock;
        _certDer = certDer;
        _keySeed = keySeed;
    }

    /// <summary>Closes the connection (no alert).</summary>
    public void Close()
    {
        if (_state == StateClosed)
            return;
        _state = StateClosed;
        _sock.Close();
    }

    /// <summary>Sends close_notify (best effort) and closes.</summary>
    public void CloseGraceful()
    {
        if (_state == StateConnected)
        {
            var alert = new byte[] { 1, AlertCloseNotify };
            SendRecord(CtAlert, alert, 0, alert.Length);
        }
        Close();
    }

    // ==================== Driving ====================

    /// <summary>
    /// Advances the handshake as far as the buffered socket data allows.
    /// Returns true when application data may now be read/written.
    /// </summary>
    public bool Step()
    {
        if (_state == StateClosed || _state == StateError)
            return false;
        var scratch = new byte[1];
        ProcessRecords(scratch, 0, 0);
        return _state == StateConnected;
    }

    /// <summary>
    /// Reads available application data. Returns the number of plaintext
    /// bytes copied (0 = none available yet), or -1 when the connection
    /// is closed/errored.
    /// </summary>
    public int ReadApp(byte[] destination, int offset, int maxLength)
    {
        if (_state == StateClosed || _state == StateError)
            return -1;
        if (_state != StateConnected)
        {
            Step();
            if (_state == StateClosed || _state == StateError)
                return -1;
            if (_state != StateConnected && _appPendingLen == 0)
                return 0;
        }
        if (_appPendingLen == 0)
            ProcessRecords(destination, offset, maxLength);
        if (_state == StateClosed || _state == StateError)
            return -1;
        return DrainPending(destination, offset, maxLength);
    }

    /// <summary>Sends application data as one or more records.</summary>
    public void WriteApp(byte[] data, int offset, int length)
    {
        if (_state != StateConnected)
            return;
        int pos = 0;
        while (pos < length)
        {
            int chunk = length - pos;
            if (chunk > 16000)
                chunk = 16000;
            SendRecord(CtApplicationData, data, offset + pos, chunk);
            pos += chunk;
        }
    }

    // ==================== Record layer ====================

    private readonly byte[] _appPending = new byte[16384];
    private int _appPendingLen;

    private void StageApp(byte[] data, int offset, int length)
    {
        for (int i = 0; i < length && _appPendingLen < _appPending.Length; i++)
            _appPending[_appPendingLen++] = data[offset + i];
    }

    private int DrainPending(byte[] destination, int offset, int maxLength)
    {
        int n = _appPendingLen < maxLength ? _appPendingLen : maxLength;
        for (int i = 0; i < n; i++)
            destination[offset + i] = _appPending[i];
        for (int i = n; i < _appPendingLen; i++)
            _appPending[i - n] = _appPending[i];
        _appPendingLen -= n;
        return n;
    }

    /// <summary>
    /// Processes all complete records in the rx buffer. Decrypted
    /// handshake messages advance the state machine; application data is
    /// staged and returned.
    /// </summary>
    private int ProcessRecords(byte[] destination, int offset, int maxLength)
    {
        ReceiveMore();

        while (_state != StateClosed && _state != StateError)
        {
            if (_rxLen < 5)
                break;
            byte type = _rx[0];
            int recLen = (_rx[3] << 8) | _rx[4];
            if (recLen > 16384)
            {
                Fail();
                break;
            }

            if (type == CtChangeCipherSpec && recLen <= 1)
            {
                // Middlebox-compat CCS: plaintext, ignored.
                if (_rxLen < 5 + recLen)
                    break;
                Consume(5 + recLen);
                continue;
            }

            if (_rxProtection == 0)
            {
                if (_rxLen < 5 + recLen)
                    break;
                if (type == CtHandshake)
                {
                    AppendHandshake(_rx, 5, recLen);
                    Consume(5 + recLen);
                    if (_state == StateWaitClientHello)
                        HandleClientHello();
                }
                else
                {
                    Fail();
                }
                continue;
            }

            // Encrypted record: 5-byte header + ciphertext + 16-byte tag;
            // the record length field INCLUDES the tag (RFC 8446 5.2).
            if (recLen < 17)
            {
                Fail();
                break;
            }
            if (_rxLen < 5 + recLen)
                break;

            int ctLen = recLen - 16;
            var header = new byte[5];
            for (int i = 0; i < 5; i++)
                header[i] = _rx[i];
            var tag = new byte[16];
            for (int i = 0; i < 16; i++)
                tag[i] = _rx[5 + ctLen + i];
            byte[] nonce = BuildNonce(_rxIv, _rxSeq);
            var aead = new AesGcm(_rxKey);
            bool ok = aead.Open(nonce, header, _rx, 5, ctLen, tag, out byte[] plain);
            if (!ok)
            {
                Console.WriteLine("[web] tls: record decrypt failed (seq " + IntStr((int)_rxSeq) + ")");
                SendAlert(20);   // bad_record_mac
                Fail();
                return -1;
            }
            _rxSeq++;
            Consume(5 + recLen);

            // Inner plaintext = content || content_type || zeros.
            int contentEnd = ctLen - 1;
            while (contentEnd >= 0 && plain[contentEnd] == 0)
                contentEnd--;
            if (contentEnd < 0)
                continue;
            byte innerType = plain[contentEnd];

            if (innerType == CtApplicationData)
            {
                StageApp(plain, 0, contentEnd);
            }
            else if (innerType == CtHandshake)
            {
                AppendHandshake(plain, 0, contentEnd);
                if (_state == StateWaitClientFinished)
                    HandleClientFinished();
            }
            else if (innerType == CtAlert)
            {
                CloseGraceful();
            }
            else
            {
                Fail();
            }
        }
        return DrainPending(destination, offset, maxLength);
    }

    private void Fail()
    {
        if (_state == StateClosed)
            return;
        _state = StateError;
        _sock.Close();
    }

    private static byte[] BuildNonce(byte[] iv, ulong seq)
    {
        var nonce = new byte[12];
        for (int i = 0; i < 12; i++)
            nonce[i] = iv[i];
        for (int i = 0; i < 8; i++)
            nonce[11 - i] ^= (byte)(seq >> (8 * i));
        return nonce;
    }

    private void SendRecord(byte type, byte[] data, int offset, int length)
    {
        byte[] wire;
        if (_txProtection == 0)
        {
            wire = new byte[5 + length];
            wire[0] = type;
            wire[1] = 0x03;
            wire[2] = 0x03;
            wire[3] = (byte)(length >> 8);
            wire[4] = (byte)length;
            for (int i = 0; i < length; i++)
                wire[5 + i] = data[offset + i];
        }
        else
        {
            int innerLen = length + 1;
            var inner = new byte[innerLen];
            for (int i = 0; i < length; i++)
                inner[i] = data[offset + i];
            inner[length] = type;
            var header = new byte[5];
            header[0] = CtApplicationData;
            header[1] = 0x03;
            header[2] = 0x03;
            header[3] = (byte)((innerLen + 16) >> 8);
            header[4] = (byte)(innerLen + 16);
            byte[] nonce = BuildNonce(_txIv, _txSeq);
            var aead = new AesGcm(_txKey);
            byte[] sealed_ = aead.Seal(nonce, header, inner);
            _txSeq++;
            wire = new byte[5 + sealed_.Length];
            for (int i = 0; i < 5; i++)
                wire[i] = header[i];
            for (int i = 0; i < sealed_.Length; i++)
                wire[5 + i] = sealed_[i];
        }
        SendAll(wire);
    }

    private void SendAll(byte[] data)
    {
        int sent = 0;
        int guard = 0;
        while (sent < data.Length && guard < 128)
        {
            guard++;
            int n;
            fixed (byte* p = data)
            {
                n = _sock.Send(p + sent, data.Length - sent);
            }
            if (n <= 0)
                return;
            sent += n;
        }
    }

    private void ReceiveMore()
    {
        while (_rxLen < _rx.Length)
        {
            int n;
            fixed (byte* p = _rx)
            {
                n = _sock.Receive(p + _rxLen, _rx.Length - _rxLen);
            }
            if (n <= 0)
                return;
            _rxLen += n;
            if (n < 1024)
                return;
        }
    }

    private void Consume(int count)
    {
        for (int i = count; i < _rxLen; i++)
            _rx[i - count] = _rx[i];
        _rxLen -= count;
    }

    private void AppendHandshake(byte[] data, int offset, int length)
    {
        for (int i = 0; i < length; i++)
        {
            if (_hsLen >= _hs.Length)
                return;
            _hs[_hsLen++] = data[offset + i];
        }
    }

    // ==================== Handshake ====================

    private void HandleClientHello()
    {
        Console.WriteLine("[web] tls: clienthello received (" + IntStr(_hsLen) + " bytes)");
        // Need the full handshake message.
        if (_hsLen < 4)
            return;
        int bodyLen = (_hs[1] << 16) | (_hs[2] << 8) | _hs[3];
        if (_hs[0] != HtClientHello || _hsLen < 4 + bodyLen)
            return;

        var body = new byte[bodyLen];
        for (int i = 0; i < bodyLen; i++)
            body[i] = _hs[4 + i];
        AppendTranscript(_hs, 0, 4 + bodyLen);

        // Parse ClientHello.
        var r = new TlsReader(body, 0, body.Length);
        r.U16();                       // legacy_version
        r.Bytes(32);                   // client random
        int sidLen = r.U8();
        byte[] sessionId = r.Bytes(sidLen);
        int suitesLen = r.U16();
        bool has1301 = false;
        bool has1302 = false;
        for (int i = 0; i + 1 < suitesLen; i += 2)
        {
            ushort cs = (ushort)r.U16();
            if (cs == 0x1301)
                has1301 = true;
            else if (cs == 0x1302)
                has1302 = true;
        }
        int compLen = r.U8();
        r.Skip(compLen);
        int extTotal = r.U16();
        int extEnd = r.Position + extTotal;

        byte[] clientX25519 = null;
        bool versionOk = false;
        bool sigAlgOk = false;
        string sni = null;

        while (r.Position + 4 <= extEnd)
        {
            int extType = r.U16();
            int extLen = r.U16();
            int extStart = r.Position;
            if (extType == 43)          // supported_versions
            {
                int listLen = r.U8();
                for (int i = 0; i + 1 < listLen; i += 2)
                {
                    if (r.U16() == 0x0304)
                        versionOk = true;
                }
            }
            else if (extType == 51)     // key_share
            {
                int sharesLen = r.U16();
                int sharesEnd = r.Position + sharesLen;
                while (r.Position + 4 <= sharesEnd)
                {
                    int group = r.U16();
                    int klen = r.U16();
                    if (group == 0x001D && klen == 32)
                    {
                        clientX25519 = r.Bytes(32);
                    }
                    else
                    {
                        r.Skip(klen);
                    }
                }
            }
            else if (extType == 13)     // signature_algorithms
            {
                int listLen = r.U16();
                for (int i = 0; i + 1 < listLen; i += 2)
                {
                    if (r.U16() == 0x0807)
                        sigAlgOk = true;
                }
            }
            else if (extType == 0)      // server_name
            {
                int listLen = r.U16();
                int listStart = r.Position;
                int nameType = r.U8();
                int nameLen = r.U16();
                if (nameType == 0 && nameLen > 0 && nameLen < 256)
                {
                    var chars = new char[nameLen];
                    for (int i = 0; i < nameLen; i++)
                        chars[i] = (char)(byte)r.U8();
                    sni = new string(chars);
                }
                r.Position = listStart + listLen;
            }
            // Skip to the end of this extension regardless.
            r.Position = extStart + extLen;
        }

        if (!versionOk || clientX25519 == null || !sigAlgOk)
        {
            Console.Write("[web] tls: hello rejected ver=");
            Console.Write(IntStr(versionOk ? 1 : 0));
            Console.Write(" x25519=");
            Console.Write(IntStr(clientX25519 == null ? 0 : 1));
            Console.Write(" sig=");
            Console.Write(IntStr(sigAlgOk ? 1 : 0));
            Console.WriteLine("");
            SendAlert(AlertHandshakeFailure);
            Close();
            return;
        }
        _serverName = sni;

        if (has1301)
        {
            _suite = 0x1301;
            _hashKind = HashKind.Sha256;
            _hashLen = 32;
            _keyLen = 16;
        }
        else if (has1302)
        {
            _suite = 0x1302;
            _hashKind = HashKind.Sha384;
            _hashLen = 48;
            _keyLen = 32;
        }
        else
        {
            SendAlert(AlertHandshakeFailure);
            Close();
            return;
        }

        // ECDHE.
        byte[] seed = Csprng.GetBytes(32);
        byte[] serverPub = X25519.ScalarMultBase(seed);
        byte[] shared = X25519.ScalarMult(seed, clientX25519);

        // ServerHello.
        var sh = new TlsWriter(128);
        sh.U16(0x0303);
        byte[] serverRandom = Csprng.GetBytes(32);
        sh.Bytes(serverRandom, 0, 32);
        sh.U8((byte)sessionId.Length);
        sh.Bytes(sessionId, 0, sessionId.Length);
        sh.U16(_suite);
        sh.U8(0);
        var exts = new TlsWriter(64);
        exts.U16(43);
        exts.U16(2);
        exts.U16(0x0304);
        exts.U16(51);
        exts.U16(36);
        exts.U16(0x001D);
        exts.U16(32);
        exts.Bytes(serverPub, 0, 32);
        sh.U16(exts.Length);
        sh.Bytes(exts.Buffer, 0, exts.Length);
        SendHandshake(HtServerHello, sh.Buffer, 0, sh.Length);
        Console.Write("[web] tls: server hello sent suite=");
        Console.Write(IntStr(_suite));
        Console.WriteLine("");

        // Key schedule (RFC 8446 section 7.1). Note: the "derived"
        // secrets hash the EMPTY transcript, not the current one.
        byte[] zeros = new byte[_hashLen];
        byte[] emptyHash = HashBytes(new byte[0]);
        byte[] earlySecret = Hkdf.Extract(_hashKind, null, zeros, 0, zeros.Length);
        byte[] derived = DeriveSecret(earlySecret, "derived", emptyHash);
        byte[] handshakeSecret = Hkdf.Extract(_hashKind, derived, shared, 0, 32);
        _clientHsTraffic = DeriveSecret(handshakeSecret, "c hs traffic", HashTranscript());
        _serverHsTraffic = DeriveSecret(handshakeSecret, "s hs traffic", HashTranscript());
        byte[] derived2 = DeriveSecret(handshakeSecret, "derived", emptyHash);
        byte[] masterSecret = Hkdf.Extract(_hashKind, derived2, zeros, 0, zeros.Length);

        // Switch TX to handshake protection.
        _txKey = ExpandLabel(_serverHsTraffic, "key", null, _keyLen);
        _txIv = ExpandLabel(_serverHsTraffic, "iv", null, 12);
        _txSeq = 0;
        _txProtection = 1;

        // Middlebox-compat CCS then the encrypted flight.
        byte[] ccs = new byte[] { CtChangeCipherSpec, 0x03, 0x03, 0x00, 0x01, 0x01 };
        SendAll(ccs);
        Console.WriteLine("[web] tls: ccs sent");

        // EncryptedExtensions (no extensions).
        var ee = new TlsWriter(8);
        ee.U16(0);
        SendHandshake(HtEncryptedExtensions, ee.Buffer, 0, ee.Length);
        Console.WriteLine("[web] tls: encrypted extensions sent");

        // Certificate.
        var certW = new TlsWriter(_certDer.Length + 16);
        certW.U8(0);                                  // request context
        certW.U24(_certDer.Length + 5);               // entry: 3 len + cert + 2 ext
        certW.U24(_certDer.Length);
        certW.Bytes(_certDer, 0, _certDer.Length);
        certW.U16(0);
        SendHandshake(HtCertificate, certW.Buffer, 0, certW.Length);
        Console.Write("[web] tls: certificate sent (");
        Console.Write(IntStr(_certDer.Length));
        Console.WriteLine(" bytes)");

        // CertificateVerify.
        byte[] th = HashTranscript();
        byte[] cvContent = BuildCertVerifyContent(th);
        byte[] signature = Ed25519.Sign(_keySeed, cvContent);
        var cv = new TlsWriter(signature.Length + 8);
        cv.U16(0x0807);
        cv.U16(signature.Length);
        cv.Bytes(signature, 0, signature.Length);
        SendHandshake(HtCertificateVerify, cv.Buffer, 0, cv.Length);
        Console.WriteLine("[web] tls: certificate verify sent");

        // Finished.
        byte[] finishedKey = ExpandLabel(_serverHsTraffic, "finished", null, _hashLen);
        byte[] verifyData = Hmac.Compute(_hashKind, finishedKey, HashTranscript());
        SendHandshake(HtFinished, verifyData, 0, verifyData.Length);
        Console.WriteLine("[web] tls: finished sent");

        // Application secrets (transcript through server Finished).
        _clientApTraffic = DeriveSecret(masterSecret, "c ap traffic", HashTranscript());
        _serverApTraffic = DeriveSecret(masterSecret, "s ap traffic", HashTranscript());

        // Switch TX to application keys; keep RX on handshake keys.
        _txKey = ExpandLabel(_serverApTraffic, "key", null, _keyLen);
        _txIv = ExpandLabel(_serverApTraffic, "iv", null, 12);
        _txSeq = 0;
        _txProtection = 2;
        _rxKey = ExpandLabel(_clientHsTraffic, "key", null, _keyLen);
        _rxIv = ExpandLabel(_clientHsTraffic, "iv", null, 12);
        _rxSeq = 0;
        _rxProtection = 1;

        // The ClientHello has been consumed; the next handshake message
        // (the client Finished) must be reassembled from a clean buffer.
        _hsLen = 0;

        _state = StateWaitClientFinished;
        Console.WriteLine("[web] tls: waiting for client finished");
    }

    private void HandleClientFinished()
    {
        if (_hsLen < 4)
            return;
        int bodyLen = (_hs[1] << 16) | (_hs[2] << 8) | _hs[3];
        if (_hs[0] != HtFinished || _hsLen < 4 + bodyLen)
            return;

        var body = new byte[bodyLen];
        for (int i = 0; i < bodyLen; i++)
            body[i] = _hs[4 + i];

        byte[] finishedKey = ExpandLabel(_clientHsTraffic, "finished", null, _hashLen);
        byte[] expected = Hmac.Compute(_hashKind, finishedKey, HashTranscript());
        bool ok = bodyLen == expected.Length;
        if (ok)
        {
            for (int i = 0; i < bodyLen; i++)
            {
                if (body[i] != expected[i])
                {
                    ok = false;
                    break;
                }
            }
        }
        if (!ok)
        {
            SendAlert(20);   // bad_record_mac
            Close();
            return;
        }
        AppendTranscript(_hs, 0, 4 + bodyLen);
        _hsLen = 0;

        // Switch RX to application keys.
        _rxKey = ExpandLabel(_clientApTraffic, "key", null, _keyLen);
        _rxIv = ExpandLabel(_clientApTraffic, "iv", null, 12);
        _rxSeq = 0;
        _rxProtection = 2;
        _state = StateConnected;
    }

    // ==================== Helpers ====================

    private void SendHandshake(byte type, byte[] data, int offset, int length)
    {
        var msg = new byte[4 + length];
        msg[0] = type;
        msg[1] = (byte)(length >> 16);
        msg[2] = (byte)(length >> 8);
        msg[3] = (byte)length;
        for (int i = 0; i < length; i++)
            msg[4 + i] = data[offset + i];
        SendRecord(CtHandshake, msg, 0, msg.Length);
        AppendTranscript(msg, 0, msg.Length);
    }

    private void SendAlert(byte description)
    {
        var alert = new byte[] { 2, description };
        if (_txProtection == 0)
        {
            var raw = new byte[] { CtAlert, 0x03, 0x03, 0x00, 0x02, 2, description };
            SendAll(raw);
        }
        else
        {
            SendRecord(CtAlert, alert, 0, 2);
        }
    }

    private void AppendTranscript(byte[] data, int offset, int length)
    {
        if (_transcriptLen + length > _transcript.Length)
        {
            var bigger = new byte[(_transcriptLen + length) * 2];
            for (int i = 0; i < _transcriptLen; i++)
                bigger[i] = _transcript[i];
            _transcript = bigger;
        }
        for (int i = 0; i < length; i++)
            _transcript[_transcriptLen++] = data[offset + i];
    }

    private byte[] HashTranscript()
    {
        var data = new byte[_transcriptLen];
        for (int i = 0; i < _transcriptLen; i++)
            data[i] = _transcript[i];
        return HashBytes(data);
    }

    private byte[] HashBytes(byte[] data)
    {
        if (_hashKind == HashKind.Sha384)
            return Sha384.Hash(data);
        return Sha256.Hash(data);
    }

    private static byte[] BuildCertVerifyContent(byte[] transcriptHash)
    {
        // 64 spaces || context string || 0x00 || transcript hash.
        byte[] context = new byte[]
        {
            0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20,
            0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20,
            0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20,
            0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20,
            0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20,
            0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20,
            0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20,
            0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20,
        };
        byte[] label = Ascii("TLS 1.3, server CertificateVerify");
        var content = new byte[64 + label.Length + 1 + transcriptHash.Length];
        int pos = 0;
        for (int i = 0; i < 64; i++)
            content[pos++] = context[i];
        for (int i = 0; i < label.Length; i++)
            content[pos++] = label[i];
        content[pos++] = 0;
        for (int i = 0; i < transcriptHash.Length; i++)
            content[pos++] = transcriptHash[i];
        return content;
    }

    private byte[] DeriveSecret(byte[] secret, string label, byte[] transcriptHash)
    {
        return ExpandLabel(secret, label, transcriptHash, _hashLen);
    }

    private byte[] ExpandLabel(byte[] secret, string label, byte[] context, int length)
    {
        byte[] fullLabel = Ascii("tls13 ");
        var info = new TlsWriter(64);
        info.U16(length);
        info.U8((byte)(fullLabel.Length + label.Length));
        info.Bytes(fullLabel, 0, fullLabel.Length);
        byte[] labelBytes = Ascii(label);
        info.Bytes(labelBytes, 0, labelBytes.Length);
        int ctxLen = context == null ? 0 : context.Length;
        info.U8((byte)ctxLen);
        if (ctxLen > 0)
            info.Bytes(context, 0, ctxLen);
        return Hkdf.Expand(_hashKind, secret, Slice(info), length);
    }

    private static byte[] Slice(TlsWriter w)
    {
        var result = new byte[w.Length];
        for (int i = 0; i < w.Length; i++)
            result[i] = w.Buffer[i];
        return result;
    }

    private static byte[] Ascii(string s)
    {
        var bytes = new byte[s.Length];
        for (int i = 0; i < s.Length; i++)
            bytes[i] = (byte)s[i];
        return bytes;
    }

    private static string HexOf(byte[] data, int offset, int len)
    {
        var digits = new char[] { '0', '1', '2', '3', '4', '5', '6', '7',
                                  '8', '9', 'a', 'b', 'c', 'd', 'e', 'f' };
        var chars = new char[len * 2];
        for (int i = 0; i < len; i++)
        {
            chars[i * 2] = digits[data[offset + i] >> 4];
            chars[i * 2 + 1] = digits[data[offset + i] & 15];
        }
        return new string(chars);
    }

    private static string IntStr(int value)
    {
        if (value == 0)
            return "0";
        bool neg = value < 0;
        if (neg)
            value = -value;
        var digits = new char[12];
        int n = 0;
        while (value > 0)
        {
            digits[n++] = (char)('0' + (value % 10));
            value /= 10;
        }
        if (neg)
            digits[n++] = '-';
        var result = new char[n];
        for (int i = 0; i < n; i++)
            result[i] = digits[n - 1 - i];
        return new string(result);
    }
}

/// <summary>Byte reader for TLS structures (JIT-world safe).</summary>
public sealed class TlsReader
{
    private readonly byte[] _data;
    private readonly int _end;
    private int _pos;

    /// <summary>Creates a reader over data[offset..offset+length).</summary>
    public TlsReader(byte[] data, int offset, int length)
    {
        _data = data;
        _pos = offset;
        _end = offset + length;
    }

    /// <summary>Current read position.</summary>
    public int Position
    {
        get => _pos;
        set => _pos = value;
    }

    /// <summary>Reads one byte.</summary>
    public int U8() => _pos < _end ? _data[_pos++] : 0;

    /// <summary>Reads one big-endian uint16.</summary>
    public int U16()
    {
        int hi = U8();
        int lo = U8();
        return (hi << 8) | lo;
    }

    /// <summary>Reads one big-endian uint24.</summary>
    public int U24()
    {
        int a = U8();
        int b = U8();
        int c = U8();
        return (a << 16) | (b << 8) | c;
    }

    /// <summary>Reads <paramref name="count"/> bytes (blank when short).</summary>
    public byte[] Bytes(int count)
    {
        var result = new byte[count];
        for (int i = 0; i < count && _pos < _end; i++)
            result[i] = _data[_pos++];
        return result;
    }

    /// <summary>Skips <paramref name="count"/> bytes.</summary>
    public void Skip(int count) => _pos += count;
}

/// <summary>Append-only byte writer for TLS structures (JIT-world safe).</summary>
public sealed class TlsWriter
{
    private byte[] _buf;
    private int _len;

    /// <summary>Creates a writer with the given initial capacity.</summary>
    public TlsWriter(int capacity)
    {
        _buf = new byte[capacity < 16 ? 16 : capacity];
    }

    /// <summary>Backing buffer (valid bytes are [0, Length)).</summary>
    public byte[] Buffer => _buf;

    /// <summary>Number of bytes written.</summary>
    public int Length => _len;

    private void Ensure(int extra)
    {
        if (_len + extra <= _buf.Length)
            return;
        int size = _buf.Length * 2;
        while (size < _len + extra)
            size *= 2;
        var bigger = new byte[size];
        for (int i = 0; i < _len; i++)
            bigger[i] = _buf[i];
        _buf = bigger;
    }

    /// <summary>Appends one byte.</summary>
    public void U8(byte value)
    {
        Ensure(1);
        _buf[_len++] = value;
    }

    /// <summary>Appends a big-endian uint16.</summary>
    public void U16(int value)
    {
        Ensure(2);
        _buf[_len++] = (byte)(value >> 8);
        _buf[_len++] = (byte)value;
    }

    /// <summary>Appends a big-endian uint24.</summary>
    public void U24(int value)
    {
        Ensure(3);
        _buf[_len++] = (byte)(value >> 16);
        _buf[_len++] = (byte)(value >> 8);
        _buf[_len++] = (byte)value;
    }

    /// <summary>Appends raw bytes.</summary>
    public void Bytes(byte[] data, int offset, int count)
    {
        Ensure(count);
        for (int i = 0; i < count; i++)
            _buf[_len++] = data[offset + i];
    }
}
