// NeutrinoOS korlib - Event handling delegates and types

namespace System
{
    /// <summary>
    /// Represents the base class for classes that contain event data.
    /// </summary>
    public class EventArgs
    {
        /// <summary>
        /// Provides a value to use with events that do not have event data.
        /// </summary>
        public static readonly EventArgs Empty = new EventArgs();

        /// <summary>
        /// Initializes a new instance of the EventArgs class.
        /// </summary>
        public EventArgs() { }
    }

    /// <summary>
    /// Represents the method that will handle an event that has no event data.
    /// </summary>
    /// <param name="sender">The source of the event.</param>
    /// <param name="e">An object that contains no event data.</param>
    public delegate void EventHandler(object? sender, EventArgs e);

    /// <summary>
    /// Represents the method that will handle an event when the event provides data.
    /// </summary>
    /// <typeparam name="TEventArgs">The type of the event data generated by the event.</typeparam>
    /// <param name="sender">The source of the event.</param>
    /// <param name="e">An object that contains the event data.</param>
    public delegate void EventHandler<TEventArgs>(object? sender, TEventArgs e);
}
